package cl.ramona.incidenciaservice.service.impl;
import cl.ramona.incidenciaservice.client.*; import cl.ramona.incidenciaservice.dto.request.*; import cl.ramona.incidenciaservice.dto.response.*; import cl.ramona.incidenciaservice.entity.Incidencia; import cl.ramona.incidenciaservice.enums.EstadoIncidencia; import cl.ramona.incidenciaservice.exception.ResourceNotFoundException; import cl.ramona.incidenciaservice.repository.IncidenciaRepository;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.time.LocalDateTime; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class IncidenciaServiceImplTest {
 @Mock IncidenciaRepository repo; @Mock SolicitudClient solicitudClient; @Mock UsuarioClient usuarioClient; @InjectMocks IncidenciaServiceImpl service;
 UsuarioResponse user(Long id){return new UsuarioResponse(id,"Ana","Díaz","a@b.cl",null,null,true,null,new RolResponse(1L,"CLIENTE"),null,null);} SolicitudResumenResponse sol(){return new SolicitudResumenResponse(10L,"RAM-20260713-0001");}
 Incidencia inc(){return Incidencia.builder().id(1L).solicitudEnvioId(10L).titulo("Daño").descripcion("Caja dañada").estado(EstadoIncidencia.ABIERTA).creadaPorId(2L).fechaCreacion(LocalDateTime.now()).fechaActualizacion(LocalDateTime.now()).build();}
 @Test void crearSinAsignado(){when(solicitudClient.obtener(10L)).thenReturn(sol());when(usuarioClient.obtener(2L)).thenReturn(user(2L));when(repo.save(any())).thenAnswer(i->{Incidencia x=i.getArgument(0);x.setId(1L);return x;});var r=service.crearIncidencia(new IncidenciaRequest(10L,"Daño","Caja dañada",2L,null));assertEquals(EstadoIncidencia.ABIERTA,r.estado());assertNull(r.asignadaA());}
 @Test void crearConAsignado(){when(solicitudClient.obtener(10L)).thenReturn(sol());when(usuarioClient.obtener(2L)).thenReturn(user(2L));when(usuarioClient.obtener(3L)).thenReturn(user(3L));when(repo.save(any())).thenAnswer(i->{Incidencia x=i.getArgument(0);x.setId(1L);return x;});var r=service.crearIncidencia(new IncidenciaRequest(10L,"Daño","Caja dañada",2L,3L));assertEquals(3L,r.asignadaA().id());}
 @Test void obtenerInexistente(){when(repo.findById(99L)).thenReturn(Optional.empty());assertThrows(ResourceNotFoundException.class,()->service.obtenerPorId(99L));}
 @Test void listarPorSolicitudValidaSolicitud(){when(solicitudClient.obtener(10L)).thenReturn(sol());when(repo.findBySolicitudEnvioId(10L)).thenReturn(List.of());assertTrue(service.listarPorSolicitud(10L).isEmpty());verify(solicitudClient).obtener(10L);}
 @Test void listarPorEstado(){when(repo.findByEstado(EstadoIncidencia.ABIERTA)).thenReturn(List.of(inc()));when(solicitudClient.obtener(10L)).thenReturn(sol());when(usuarioClient.obtener(2L)).thenReturn(user(2L));assertEquals(1,service.listarPorEstado(EstadoIncidencia.ABIERTA).size());}
 @Test void actualizarEstadoConAsignado(){Incidencia i=inc();when(repo.findById(1L)).thenReturn(Optional.of(i));when(usuarioClient.obtener(3L)).thenReturn(user(3L));when(repo.save(i)).thenReturn(i);when(solicitudClient.obtener(10L)).thenReturn(sol());when(usuarioClient.obtener(2L)).thenReturn(user(2L));var r=service.actualizarEstado(1L,new ActualizarEstadoIncidenciaRequest(EstadoIncidencia.EN_PROCESO,3L));assertEquals(EstadoIncidencia.EN_PROCESO,r.estado());assertEquals(3L,r.asignadaA().id());}
 @Test void actualizarEstadoConservaAsignado(){Incidencia i=inc();i.setAsignadaAId(3L);when(repo.findById(1L)).thenReturn(Optional.of(i));when(repo.save(i)).thenReturn(i);when(solicitudClient.obtener(10L)).thenReturn(sol());when(usuarioClient.obtener(2L)).thenReturn(user(2L));when(usuarioClient.obtener(3L)).thenReturn(user(3L));var r=service.actualizarEstado(1L,new ActualizarEstadoIncidenciaRequest(EstadoIncidencia.RESUELTA,null));assertEquals(3L,r.asignadaA().id());}
}
