FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -B -DskipTests clean package
FROM eclipse-temurin:21-jre
WORKDIR /app
RUN useradd --system --uid 10001 ramona
COPY --from=build /app/target/seguimiento-service-0.0.1-SNAPSHOT.jar app.jar
USER ramona
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
