spring:
  datasource:
    url: jdbc:oracle:thin:@tcps://adb.sa-valparaiso-1.oraclecloud.com:1522/gf8a4acc6bb157d_mjswhxc6myd29o1l_medium.adb.oraclecloud.com?wallet_location=C:/Users/rodri/Downloads/Wallet_MJSWHXC6MYD29O1L
    username: ADMIN
    password: Ramona_express27
    driver-class-name: oracle.jdbc.OracleDriver